### ISSUE TITLE
Server Registration

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum#10]
1. Application Name
2. Label for Responsible Agent
3. Contact E-mail for Agent

- Store in database (private collection or separate storage?)
- generate and return API key
  - A fake Latin generator would be fun
  - Delay for approval process or immediate use?
- Mailer may be required

**Comment by thehabes** [comment]
This sits out on the dev server annotationstore web app.  I will bring it into RERUM and hit the annotationstore registration APIs so it is a piece of the RERUM web app and can move with it.

**Comment by thehabes** [comment]
not ready yet, but can be seen at http://165.134.241.141/rerum/#/register

**Comment by thehabes** [comment]
Registration has been upgraded.  If the IP is not a duplicate, it registers that IP with the white list AND creates an Agent connected with that IP in the annotation store.  We can now use these Agents as registered users with RERUM and can think about CRUD operations around the Agents.  We can hinge on the fact that each IP will only have 1 Agent associated with it.

We can begin to develop the API key verification in #25.  

We can think about token-based authentication (like OpenID and Oauth).

We can begin to think about how we manage agents on a management page (#11)
