### ISSUE TITLE
Pretty print output in returned objects

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum#27]
In GCS, ancestors may help here.

Versions are the history of each object. When an update is made, the old version is first deprecated into a new object with its date of demotion. If someone wants to request the version history (or a specific one) we'll need to allow for that.

Forked versions may share a history, but lead to multiple current versions. We'll need to consider use cases carefully.

Applications may also force an update without versioning for minor changes, though this ought to be discouraged.

**Comment by thehabes** [comment]
We could make a global API response handler for this, or just make sure to format all of our returns in each API response we make.  I lean towards a global API response handler.
