### ISSUE TITLE
Someone else started RERUM in 2016

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum#28]
https://ict-rerum.eu/

Interesting. In the realm of what we are doing, but very different. They didn't even call it RERUM until last year. It is made from **RE**liable, **R**esilient and sec**U**re IoT for s**M**art city applications, which makes my brain explode.

**Comment by cubap** [comment]
They even have a RERUM Consortium, so we missed that by a narrow margin. I mean, they started in with RERUM at a conference on November 21, 2016. Please...

**Comment by thehabes** [comment]
HAHA this is crazy
