### ISSUE TITLE
RERUM options

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/rerum#41]
Add __rerum array for options

**Comment by thehabes** [comment]
Need to fix the update functions because they do not look in __rerum for the properties we moved in there.

**Comment by cubap** [comment]
not an array anymore

* `APIversion`—1.0.0 (API version under which it was created)
* `history.prime`—"root" or URI of first version
* `history.next`—Array of URIs for direct updates to this object
* `history.previous`—URI of the object this updated (null for prime)
* `releases.previous`—null or URI of single upstream `isReleased` version
* `releases.next`—Array of URIs for downstream Releases
* `generatedBy`—URI of the public agent of the generating software application
* `createdAt`—creation timestamp in milliseconds
* `isOverwritten`—timestamp if update is forced after creation
* `isReleased`—null, true (meaning it is a permanent release), or false (work in progress)
