### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/rerum#47]
https://coderwall.com/p/hdmmnq/easy-automatic-nightly-backups-for-mongodb

Cron/Daemon for regular backups

**Comment by cubap** [comment]
Completed and tested. I will check to be sure it is running over the next month.
The expectation is that every MWF there is a new file replacing the one from the previous week. 
Each Monday (first 4 in a month), the file is copied into WeekABCD.
Each Quarter, the same file is copied into Q1234.
July 1, the same file is copied to Anno, whence we can copy it off-line manually.

So our unique backups map on June 30 looks like:
~~~~~~
   M  W  F , M  W  F , M  W  F , M  W  F , ...

J 01 .. .., .. .. .., .. .. .., .. .. ..,
A .. .. .., .. .. .., .. .. .., .. .. ..,
S .. .. .., .. .. .., .. .. .., .. .. ..,
O 02 .. .., .. .. .., .. .. .., .. .. ..,
N .. .. .., .. .. .., .. .. .., .. .. ..,
D .. .. .., .. .. .., .. .. .., .. .. ..,
J 03 .. .., .. .. .., .. .. .., .. .. ..,
F.. .. .., .. .. .., .. .. .., .. .. ..,
M .. .. .., .. .. .., .. .. .., .. .. ..,
A 04 .. .., .. .. .., .. .. .., .. .. ..,
M .. .. .., .. .. .., .. .. .., .. .. ..,
J 05 .. .., 06 .. .., 07 .. .., 08 09 10
