### ISSUE TITLE
Install Node or convert backend to Java

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum#8]

**Comment by thehabes** [comment]
Man I am sitting right on the edge of this.  Do we want Java or node?

**Comment by cubap** [comment]
It seems like a good year for node, but not if we can't get the ports
opened. In the long run, it wouldn't be bad to have forks of the code in
several languages, so it won't hurt to build the Java. It is not much code,
especially since there is no model validation on the saved objects.
